<h1><?php echo $this->_('About Hynage'); ?></h1>

<p>
    <?php echo $this->_('Hynage is a sample implementation of an MVC framework written in PHP 5.3.'); ?>
</p>

<p>
    <?php echo $this->_('The word <em>Hynage</em> is a tribute to the two great men named Jamie Hyneman and Adam Savage.'); ?><br />
    <?php echo $this->_('Make sure you <a href="%s">watch Adam Savage\'s Colossal Failures</a> presented by FORA.tv.', 'http://fora.tv/2009/05/30/MythBuster_Adam_Savages_Colossal_Failures'); ?>
</p>