<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
    <head>
        <meta name="content-type" content="text/html; charset=utf-8" />
        
        <title>Total Hynage!</title>
        
        <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.1.1/build/cssreset/reset-min.css" />
        <link rel="stylesheet" type="text/css" href="/css/website.css" />
        
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript" src="/js/hynage.js"></script>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div id="logo">
                    <a href="/"><img src="/images/logo.png" title="Hynage Logo" alt="Hynage Logo" /></a>
                </div>
                <div id="navigation">
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><a href="/about">About</a></li>
                    </ul>
                </div>
            </div>
            <div id="content">
                <?php echo $this->getContent(); ?>
            </div>
            <div id="footer">
                This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.
            </div>
        </div>
    </body>
</html>